name = "SolverCore"
uuid = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
version = "0.3.9"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[extensions]
SolverCoreNLPModelsExt = "NLPModels"

[compat]
NLPModels = "0.20, 0.21.5"
julia = "1.10"
