name = "SolverCore"
uuid = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
version = "0.2.3"

[deps]
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
NLPModels = "0.15, 0.16, 0.17, 0.18"
julia = "^1.6"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "LinearAlgebra", "Logging", "Test"]
